name: Cortex Code Review
description: Send PR info to Cortex backend

inputs:
  backend-url:
    description: Pervaziv backend URL
    required: false
    default: 'https://trudi-synoptistic-meanspiritedly.ngrok-free.dev/runBotScan'
  console-url:
    description: Pervaziv console URL
    required: false
    default: 'https://console.pervaziv.com'

runs:
  using: node20
  main: dist/index.js