name: Pervaziv AI Code Review
description: Security scanning that automatically analyzes your repository, displays vulnerabilities in the GitHub Security tab as code scanning alerts, and shows a detailed summary in the Actions tab with a link to the Pervaziv console.
inputs:
  backend-url:
    description: Pervaziv backend URL
    required: false
    default: 'https://trudi-synoptistic-meanspiritedly.ngrok-free.dev/runBotScan'
  console-url:
    description: Pervaziv console URL
    required: false
    default: 'https://console.pervaziv.com'

runs:
  using: node20
  main: dist/index.js